FROM node:10-alpine
ARG ANYPROXY_VERSION=3.10.6

EXPOSE 8001
EXPOSE 8002

RUN echo "#!/bin/sh" > /usr/bin/open \
  && echo "exit 0" >> /usr/bin/open \
  && chmod +x /usr/bin/open \
  && npm i -g anyproxy@$ANYPROXY_VERSION

RUN mkdir /anyproxy \
  # generate root cert
  && anyproxy --root

CMD anyproxy --intercept --file /anyproxy/anyproxy.log